### ISSUE TITLE
Syntax for defining nick in the ReadMe doesn't work

### ISSUE THREAD

**Issue by njh** [jch/em-irc#1]
Hello,

Just been trying out the example in the Readme, but there is no nick= accessor defined in EventMachine::IRC::Client:

```
client = EventMachine::IRC::Client.new do
host 'irc.freenode.net'
port '6667'
nick 'jch'
```

Should the nickname be sent in the c.on(:connect) instead?

Thanks,

nick.

**Comment by jch** [comment]
Good catch, I've pushed an update to the README. Check out spec/integration/integration_spec.rb for an example run through as well. I plan to add more unit tests to check each of these commands as well.
