### ISSUE TITLE
Unitialized constant EventMachine::IRC::Client::Logger (NameError)

### ISSUE THREAD

**Issue by Wildhoney** [jch/em-irc#6]
`/Users/Wildhoney/.rvm/gems/ruby-2.0.0-p247/gems/em-irc-0.0.2/lib/em-irc/client.rb:95:in block in run!': uninitialized constant EventMachine::IRC::Client::Logger (NameError)`

I've done nothing apart from copy-paste the example, but it doesn't appear to work. Does this relate to #5?

**Comment by llimllib** [comment]
add `require logger` and that should go away

**Comment by Wildhoney** [comment]
My goodness you're alive! Thanks :thumbsup:

**Comment by llimllib** [comment]
I'm just a dude that found the project useful and had to fix that particular bug!

**Comment by Wildhoney** [comment]
Haha, oh! Many thanks for the reply in that case.
